### ISSUE TITLE
Erro na Integração entre o Facebook e aplicação

### ISSUE THREAD

**Issue by felipeguerra19** [rafaelbss/MapaUniversitarioWeb#1]
Caro Rafael,

Ocorreu um erro no momento que eu abri a home do projeto MapaUniversitarioWeb em meu browser.
Veja a descrição do erro que o Facebook retorna:
`{
"error": {
"message": "Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.",
"type": "OAuthException",
"code": 191,
"fbtrace_id": "AfLzjAxLaOL"
}
}`
Como podemos endereçar isso?

**Comment by rafaelsantos** [comment]
Oi Felipe,

Acredito que esse erro está acontecendo porque a URL mapeada no App do
Facebook que criei está apontada para:
http://localhost:8080/MapaUniversitario.

Se quiser posso alterar a URL aqui.


​

2017-03-28 10:51 GMT-03:00 Felipe Guerra de Oliveira <
notifications@github.com>:

**Comment by rafaelsantos** [comment]
Pode incluir a URL: http://localhost:8010/MapaUniversitario-1.0.0-SNAPSHOT/

Atenciosamente,

*Felipe Guerra de Oliveira*
Arquiteto de TI

felipe.avance@luizalabs.com

**Comment by rafaelsantos** [comment]
Boa tarde Felipe,

Acabei de incluir a URL.

Verifique no projeto web, o arquivo de configuração: application.properties

E a chave base.domain.url precisa ser alterada para o valor:
http://localhost:8010
<http://localhost:8010/MapaUniversitario-1.0.0-SNAPSHOT/>.

Em 28 de março de 2017 12:13, Felipe Guerra de Oliveira <
felipe.avance@luizalabs.com> escreveu:

> Pode incluir a URL: http://localhost:8010/MapaUniversitario-1.0.0-
> SNAPSHOT/
>
> Atenciosamente,
>
> *Felipe Guerra de Oliveira*
> Arquiteto de TI
>
> felipe.avance@luizalabs.com
>
> On Tue, Mar 28, 2017 at 12:04 PM, Rafael B. S. Santos <

**Comment by felipeguerra19** [comment]
Ok, resolvi.

**Comment by rafaelsantos** [comment]
ok!

2017-03-28 14:44 GMT-03:00 Felipe Guerra de Oliveira <
notifications@github.com>:
